### ISSUE TITLE
Allow temporary redirects and restrict permanent redirects

### ISSUE THREAD

**Issue by jesperkristensen** [Geta/404handler#108]
When you set up a redirect, a 301 permanent redirect is generated. It should be possible to set up a 302 temporary redirect.

Since permanent redirects are very permanent, we would like to be able to restrict creating permanent redirects to specific users.

There is a delete button next to each redirect. This button should be removed next to permanent redirects, since they won't be deleted from user's caches, so deleting them from the UI will just make it confusing to find out what redirects we actually have. There should be a deactivate button instead.

**Comment by DrewNull** [comment]
+1 for being able to select from either 301 or 302.

**Comment by joshuajones02** [comment]
Has this been further discussed? +1 if not still available.

**Comment by taraldr** [comment]
+1, we have a use case where all pages of an alternate language responding with a 404 should redirect to the front page of that language.
`page.com/no/ -> page.com/no/ [Wildcard checked]` 
As the editors translate pages, the pages should become available, but since 301s are cached, they will always redirect to the front page of that language. If we could mark this rule as having 302 behaviour, the issue would be solved.

**Comment by absolunet-puller** [comment]
I would be very interested in an option for 302 redirects as well!

**Comment by abso-crichard** [comment]
I would be very interested in a 302 redirect option as well!

**Comment by marisks** [comment]
Implemented, so closing.
