### ISSUE TITLE
Only exact matches

### ISSUE THREAD

**Issue by andemt** [Geta/404handler#205]
Hi
We have a problem with our redirect. We only want exact match to redirect. 

If we have 
/A -> / 
Then /A/B will be redirected to /B

We want to keep /A/B with that url. 
Wildcard is not checked. 
We are using Geta.404Handler version 1.2.0 (latest)

How do we accomplish that only exact match will be redirected and not subpages?

**Comment by marisks** [comment]
Not sure what you want to achieve.
First, you had this page structure:
![image](https://user-images.githubusercontent.com/646298/101906081-13b09a80-3bc1-11eb-8a90-a2f8fc4f8e52.png)
Then you deleted page "A" and added a redirect from "/A" to "/" because page "A" does not exist and returns 404. What did you do with page "B"? How it stayed on the same URL "/A/B" after you deleted page "A"?

**Comment by andemt** [comment]
Hi
We are using for it migrating an old structure, so we wanted some urls to be redirected to one place, and sub pages to another.

For now we use INotFoundHandler to handle this.

**Comment by marisks** [comment]
Ok. Then it means that you are not keeping "/A/B" URL. It is now more clear.
Then you want to redirect "/A" -> "/" and "/A/B" -> "/C". Am I right?

**Comment by andemt** [comment]
In my case yes.

But, what is Wildcard? Is it when you have "/Page1", "/Page2" and "/Page3" and you define "/Page" with wildcard, all the pages will get redirect?

**Comment by marisks** [comment]
Form what I understand, when a wildcard is checked, it will redirect all subpages to a single page while it is unchecked - it will redirect to the matching subpage.

So if we have a redirect: /a -> /b
- with wildcard it will redirect /a/1 to /b
- without wildcard it will redirect /a/1 to /b/1

**Comment by marisks** [comment]
I have added an explanation to the docs: https://github.com/Geta/404handler#wildcards
