### ISSUE TITLE
Redirect specific URL

### ISSUE THREAD

**Issue by mkaziz** [Geta/404handler#40]
Hi folks,

I don't think the addon currently handles the following use case. I want to redirect:

`/my-site/some-page` to `/my-site/redirect-page`

but not:

`/my-site/some-page/some-other-page`

Am I missing something in the documentation? If I check the wildcard option `/my-site/some-page/some-other-page` will get redirected to `/my-site/redirect-page`. And if I don't, it will get redirected to `/my-site/redirect-page/some-other-page` Any thoughts on this?

**Comment by permagne** [comment]
Not the actual answer to your question, but keep in mind that if "/my-site/some-page/some-other-page" actually exists, it will not give a 404 error - and will not do a redirect, regardless of your redirect setup.

**Comment by mkaziz** [comment]
@permagne I wasn't aware of that. Thanks! I think that should help deal with that edge case.

**Comment by VladimirLevchuk** [comment]
Hi there,

the issue seems quite important: with redirect rule http://mysite/test => http://mysite (not a wildcard rule) we have some surprising outcome:

- [PASSED] http://mysite/test => http://mysite
- [PASSED] http://mysite/test/ => http://mysite/
- [FAILED] http://mysite/testme => http://mysite/me
- [FAILED] http://mysite/test/me => http://mysite/me
- [PASSED] http://mysite/tester => http://mysite/tester (when Tester page is actually exists in episerver tree)

**Comment by marisks** [comment]
As I remember it was fixed. If not, then please open the issue again. Find the latest version here: https://nuget.episerver.com/package/?id=Geta.404Handler
